In [2]:
%pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


# This is for CSV

### Get data from CSV

In [4]:
import pandas as pd
import numpy as np

# Load the data
data = pd.read_csv('iris.csv')
data.head(20)

sepal.length  sepal.width  petal.length  petal.width variety
0            5.1          3.5           1.4          0.2  Setosa
1            4.9          3.0           1.4          0.2  Setosa
2            4.7          3.2           1.3          0.2  Setosa
3            4.6          3.1           1.5          0.2  Setosa
4            5.0          3.6           1.4          0.2  Setosa
5            5.4          3.9           1.7          0.4  Setosa
6            4.6          3.4           1.4          0.3  Setosa
7            5.0          3.4           1.5          0.2  Setosa
8            4.4          2.9           1.4          0.2  Setosa
9            4.9          3.1           1.5          0.1  Setosa
10           5.4          3.7           1.5          0.2  Setosa
11           4.8          3.4           1.6          0.2  Setosa
12           4.8          3.0           1.4          0.1  Setosa
13           4.3          3.0           1.1          0.1  Setosa
14           5.8          4.0           1.2          0.2  Setosa
15           5.7          4.4           1.5          0.4  Setosa
16           5.4          3.9           1.3          0.4  Setosa
17           5.1          3.5           1.4          0.3  Setosa
18           5.7          3.8           1.7          0.3  Setosa
19           5.1          3.8           1.5          0.3  Setosa

In [5]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [6]:
# Seed for reproducibility
np.random.seed(0)

np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

In [7]:
np.random.normal(0,1,(3,3))

array([[ 0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574],
       [-2.55298982,  0.6536186 ,  0.8644362 ]])

### Array Indexing & Slicing

**One-dimensional subarray**

In [8]:
x1 = np.random.randint(10, size=6)  # One-dimensional array

In [9]:
x1

array([7, 2, 0, 0, 4, 5], dtype=int32)

In [10]:
x1[5], x1[0], x1[1]

(np.int32(5), np.int32(7), np.int32(2))

**Multi-dimentional array**

In [11]:
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array

In [12]:
x2

array([[5, 6, 8, 4],
       [1, 4, 9, 8],
       [1, 1, 7, 9]], dtype=int32)

In [13]:
x2[0,1]

np.int32(6)

**Slicing**
<br> x[start:stop:step]

In [14]:
x1[0:3:1]

array([7, 2, 0], dtype=int32)

In [15]:
# every other elements, every 2 steps
x1[::2]

array([7, 0, 4], dtype=int32)

In [16]:
# 2 rows, 3 columns
x2[:2, :3]

array([[5, 6, 8],
       [1, 4, 9]], dtype=int32)

### Reshaping of arrays & Transpose

In [17]:
grid = np.arange(1, 10)
grid.shape

(9,)

In [18]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
# Transpose: turn columns into rows
a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

### Array Concatenation & Spliting

In [21]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])

In [22]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [23]:
grid = np.array([[1, 2, 3], [4, 5, 6]])

In [24]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [25]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7], [6, 5, 4]])

# vertically stack the arrays
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [26]:
# horizontally stack the arrays
y = np.array([[99], [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

**Spliting**


In [27]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [28]:
np.split(arr, [1, 3])

[array([1]), array([2, 3]), array([4, 5])]

## Broadcasting and Vectorized operations
<br>broadcasting is simply a set of rules for applying binary ufuncs (addition, subtraction, mutiplication, ect.) on arryas of different sizes![alt text](image.png)

In [29]:
a = np.arange(3)

In [30]:
a

array([0, 1, 2])

In [31]:
a + 5 # add 5 to each element (broadcasting)

array([5, 6, 7])

In [32]:
b = np.ones((3,3))

In [33]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
a.shape, b.shape

((3,), (3, 3))

In [35]:
a + b

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [36]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [37]:
c = np.arange(3).reshape(3,1)

In [38]:
c

array([[0],
       [1],
       [2]])

In [39]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Manipulation & Comparing Arrays

**Agregation**
<br> Agregation = perform the same operation on number of things

In [40]:
list_number = [1, 2, 3, 4, 5]

In [41]:
ll = np.array(list_number)

In [42]:
ll

array([1, 2, 3, 4, 5])

In [43]:
sum(ll) # sum of all elements python method

np.int64(15)

In [44]:
np.sum(ll)

np.int64(15)

In [45]:
# Create massive array 
big_array = np.random.rand(1000000)

big_array[:5]

array([0.96980907, 0.65314004, 0.17090959, 0.35815217, 0.75068614])

In [46]:
big_array.size

1000000

In [47]:
%timeit sum(big_array)

40.7 ms ± 308 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [48]:
%timeit np.sum(big_array)

242 μs ± 6.56 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [49]:
np.mean(big_array)

np.float64(0.5002074853006652)

In [50]:
np.max(big_array)

np.float64(0.9999994392723005)

In [51]:
np.min(big_array)

np.float64(1.4057692298008462e-06)

## Standard deviation and variance

In [52]:
dog_height = np.array([600, 470, 170, 430, 300])

In [53]:
np.std(dog_height) # standard deviation

np.float64(147.32277488562318)

In [54]:
np.var(dog_height) # variance

np.float64(21704.0)

In [55]:
np.sqrt(np.var(dog_height)) # standard deviation

np.float64(147.32277488562318)

## Sorting array
<br> np.sort uses an quicksort algorithm

In [56]:
x = np.array([1, 4, 5, 3, 2])

np.sort(x)

array([1, 2, 3, 4, 5])

In [57]:
# A related function is argsort, which instead returns the indices of the sorted elements:
i = np.argsort(x) 
i

array([0, 4, 3, 1, 2])

**Sorting along rows and columns**

In [58]:
np.random.seed(20)

MatA = np.random.randint(0, 10, (4, 6))

In [59]:
MatA

array([[3, 9, 4, 6, 7, 2],
       [0, 6, 8, 5, 3, 0],
       [6, 6, 0, 9, 5, 7],
       [5, 2, 6, 9, 3, 3]], dtype=int32)

In [60]:
np.sort(MatA, axis=0) # sort by column

array([[0, 2, 0, 5, 3, 0],
       [3, 6, 4, 6, 3, 2],
       [5, 6, 6, 9, 5, 3],
       [6, 9, 8, 9, 7, 7]], dtype=int32)

In [61]:
np.sort(MatA, axis=1) # sort by row

array([[2, 3, 4, 6, 7, 9],
       [0, 0, 3, 5, 6, 8],
       [0, 5, 6, 6, 7, 9],
       [2, 3, 3, 5, 6, 9]], dtype=int32)

## Linear Algebra

In [62]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [63]:
B = np.array([[8, 7], [6, 5], [3, 1]])

In [64]:
# A (3x3) dot product B (3x2)
# A.dot(B)
# or
np.dot(A, B)

array([[ 29,  20],
       [ 80,  59],
       [131,  98]])

In [65]:
B @ A # same as np.dot

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

**Dot Product Example**

In [ ]:
# Number of jars sold

np.random.seed(0)

sale_amounts = np.random.randint(20, size=(5,3))

In [ ]:
sale_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]], dtype=int32)

In [ ]:
# Create weekly sales

weekly_sales = pd.DataFrame(
    sale_amounts,
    index=["Mon", "Tue", "Wed", "Thu", "Fri"],
    columns=["Almond Butter", "Peanut Butter", "Cashew Butter"],
)

In [ ]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon             12             15              0
Tue              3              3              7
Wed              9             19             18
Thu              4              6             12
Fri              1              6              7

In [ ]:
# Create prices array

prices = np.array([10, 8, 12])

In [ ]:
butter_prices = pd.DataFrame(prices.reshape(1, 3),
                             index=["Price"],
                             columns=["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [ ]:
butter_prices

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [ ]:
weekly_sales.shape, butter_prices.shape

((5, 3), (1, 3))

In [ ]:
total_prices = weekly_sales.dot(butter_prices.T)

In [ ]:
total_prices

Price
Mon    240
Tue    138
Wed    458
Thu    232
Fri    142

In [ ]:
weekly_sales["Total ($)"] = total_prices

In [ ]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total ($)
Mon             12             15              0        240
Tue              3              3              7        138
Wed              9             19             18        458
Thu              4              6             12        232
Fri              1              6              7        142

## Creating Numpy Arrays from Scratch

**zeros, ones, full, arange, linspace**

In [ ]:
# zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# ones
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
# full

np.full((3,3), 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [ ]:
# arange

np.arange(0, 10, 2) # start, stop, step

array([0, 2, 4, 6, 8])

In [66]:
# linspace

np.linspace(0, 10, 12) # 5 evenly spaced numbers between 0 and 10 (5 numbers)

array([ 0.        ,  0.90909091,  1.81818182,  2.72727273,  3.63636364,
        4.54545455,  5.45454545,  6.36363636,  7.27272727,  8.18181818,
        9.09090909, 10.        ])