# 100 exercises Numpy

In [3]:
import numpy as np

In [4]:
# Print the numpy version and the configuration

print(np.__version__)

2.2.2


In [5]:
# Create a null vector of size 10

null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
# How to find the memory size of any array

# method 1
memory_size = null_vector.size * null_vector.itemsize

# method 2
# memory_size = null_vector.nbytes

memory_size

80

In [7]:
# How to get the documentation of the numpy add function from the command line?

help(np.add)

# print(np.info(np.add))

# print(np.add.__doc__)

Help on ufunc in module numpy:

add = <ufunc 'add'>
    add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

    Add arguments element-wise.

    Parameters
    ----------
    x1, x2 : array_like
        The arrays to be added.
        If ``x1.shape != x2.shape``, they must be broadcastable to a common
        shape (which becomes the shape of the output).
    out : ndarray, None, or tuple of ndarray and None, optional
        A location into which the result is stored. If provided, it must have
        a shape that the inputs broadcast to. If not provided or None,
        a freshly-allocated array is returned. A tuple (possible only as a
        keyword argument) must have length equal to the number of outputs.
    where : array_like, optional
        This condition is broadcast over the input. At locations where the
        condition is True, the `out` array will be set to the ufunc result.
        Elsewhere, the `out` array wi

In [8]:
# Create a null vector of size 10 but the fifth value which is 1

null_vector = np.zeros(10)
null_vector[4] = 1
null_vector

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [9]:
# Create a vector with values ranging from 10 to 49

vector = np.arange(10, 50)
vector

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [10]:
# Reverse vertor

# method 1: using slicing
vector = vector[::-1]

# method 2: using flip
# vector = np.flip(vector)

# method 3: using flipud
# vector = np.flipud(vector)
vector

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [11]:
#  Create a 3x3 matrix with values ranging from 0 to 8

# method 1
new = np.arange(9).reshape(3, 3)

# method 2
# new = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])

# method 3
# new = np.array([range(3), range(3, 6), range(6, 9)])
new

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
# Find indices of non-zero elements from [1,2,0,0,4,0]

# # method 1
non_zero = np.nonzero([1, 2, 0, 0, 4, 0])

# method 2
# non_zero = np.where([1, 2, 0, 0, 4, 0])

# method 3
# non_zero = np.array([i for i, x in enumerate([1, 2, 0, 0, 4, 0]) if x != 0])
non_zero

(array([0, 1, 4]),)

In [13]:
# Create a 3x3 identity matrix

identity_matrix = np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# Create a 3x3 array with random values

# method 1
random_matrix = np.random.random((3, 3))

# method 2
# random_matrix = np.random.rand(3, 3)

# method 3
# random_matrix = np.random.random_sample((3, 3))
random_matrix

array([[0.52523496, 0.00831727, 0.73226192],
       [0.34760164, 0.56239912, 0.83116689],
       [0.47282816, 0.4779573 , 0.41793349]])

In [15]:
# Create a 3x3x3 array with random values

random_array = np.random.random((3, 3, 3))
random_array

array([[[0.47725765, 0.78887987, 0.88532321],
        [0.82177728, 0.54662652, 0.90326921],
        [0.16951418, 0.06678301, 0.34366641]],

       [[0.17753853, 0.77577612, 0.41939164],
        [0.64316395, 0.24503852, 0.37861871],
        [0.70029428, 0.17298155, 0.70798299]],

       [[0.97331831, 0.52556693, 0.18341319],
        [0.18179076, 0.8450511 , 0.37129175],
        [0.82606079, 0.46306895, 0.93772377]]])

In [16]:
# Create a 10x10 array with random values and find the minimum and maximum values

# method 1
arr = np.random.random((10,10))

arr.min(), arr.max()

(np.float64(0.0009843219049932017), np.float64(0.9826711728015486))

In [17]:
# Create a random vector of size 30 and find the mean value

# method 1 
arr = np.random.random(30)

# method 2
# arr = np.random.rand(30)

arr.mean()

np.float64(0.486830245985522)

In [18]:
# Create a 2d array with 1 on the border and 0 inside

# method 1
arr = np.ones((5, 5))
arr[1:-1, 1:-1] = 0

# method 2
# arr = np.zeros((5, 5))
# arr[0, :] = 1
# arr[-1, :] = 1
# arr[:, 0] = 1         
# arr[:, -1] = 1 

arr

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# How to add a border (filled with 0's) around an existing array?

arr = np.ones((5, 5))
arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)

arr

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [20]:
# What is the result of the following expression?

0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

In [21]:
# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

# method 1
arr = np.diag(1 + np.arange(4), k=-1)

arr


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [22]:
# Create a 8x8 matrix and fill it with a checkerboard pattern

# method 1
arr = np.zeros((8, 8), dtype=int)
arr[1::2, ::2] = 1
arr[::2, 1::2] = 1

arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [23]:
# Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

# method 1
import numpy as np

# Shape of the array
shape = (6, 7, 8)

# Element index (0-based index for 100th element is 99)
element_index = 100

# Find the index (x, y, z) using unravel_index
index = np.unravel_index(element_index, shape)

print(f"The index (x, y, z) of the 100th element is: {index}")


The index (x, y, z) of the 100th element is: (np.int64(1), np.int64(5), np.int64(4))


In [24]:
# Create a checkerboard 8x8 matrix using the tile function

# method 1
arr = np.tile(np.array([[0, 1], [1, 0]]), (4, 4))

arr

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [25]:
# Normalize a 5x5 random matrix

# method 1
arr = np.random.random((5, 5))
arr_max, arr_min = arr.max(), arr.min()
normalize_array = (arr - arr_min)/(arr_max - arr_min)

normalize_array

array([[0.18401972, 0.24841528, 0.92592851, 0.83709649, 0.59915849],
       [0.60074845, 0.25247306, 0.03351634, 0.86815824, 0.        ],
       [0.19913946, 0.961649  , 0.27261668, 0.95747555, 0.15913602],
       [0.15656972, 0.61103759, 0.05259863, 0.33999462, 0.55127606],
       [0.51866904, 0.1253187 , 0.67586636, 1.        , 0.21719129]])

In [26]:
# Create a custom dtype that describes a color as four unsigned bytes (RGBA)

# method 1
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])

color

dtype([('r', 'u1', (1,)), ('g', 'u1', (1,)), ('b', 'u1', (1,)), ('a', 'u1', (1,))])

In [27]:
# Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

matrix1 = np.random.random((5, 3))
matrix2 = np.random.random((2, 3))
matrix3 = np.dot(matrix1, matrix2.reshape(3, 2)) # make sure the shape is correct

# method 2
# matrix3 = matrix1 @ matrix2

matrix3

array([[0.4528047 , 0.64930456],
       [0.22480245, 0.54766142],
       [0.73999996, 0.98992878],
       [0.54106913, 1.28143295],
       [0.4061866 , 0.79975855]])

In [28]:
# Given a 1D array, negate all elements which are between 3 and 8, in place.

arr = np.arange(11)
arr[(3 <= arr) & (arr <= 8)] *= -1

arr

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

In [29]:
# How to round away from zero a float array ?

arr = np.random.uniform(-10, 10, 10)
arr = np.copysign(np.ceil(np.abs(arr)), arr)

arr

array([ -1.,  -7.,  -6.,   8.,   3.,  -8., -10.,  -2.,   9.,  -4.])

In [32]:
# How to find common values between two arrays?

arr1 = np.random.randint(0, 10, 10)
arr2 = np.random.randint(0, 10, 6)

intersection = np.intersect1d(arr1, arr2)

intersection

array([1, 3, 6], dtype=int32)

In [ ]:
# How to get the dates of yesterday, today and tomorrow?

yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today = np.datetime64('today', 'D')
tomorrow = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

print(f"Yesterday: {yesterday}\nToday: {today}\nTomorrow: {tomorrow}")

Yesterday: 2025-03-10
Today: 2025-03-11
Tomorrow: 2025-03-12


In [35]:
# How to get all the dates corresponding to the month of July 2016?

date_for_july_2016 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')

date_for_july_2016

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

In [37]:
# How to compute ((A+B)*(-A/2)) in place (without copy)?

A = np.ones(3) * 1
B = np.ones(3) * 2

np.add(A, B, out=B)
np.divide(A, 2, out=A)
np.negative(A, out=A)
np.multiply(A, B, out=A)

A

# How to compute ((A+B)*(-A/2)) in place (with copy)?

# A = np.ones(3) * 1
# B = np.ones(3) * 2

# C = np.add(A, B)
# D = np.divide(A, 2)
# E = np.negative(D)
# F = np.multiply(C, E)

# F

array([-1.5, -1.5, -1.5])

In [38]:
# Extract the integer part of a random array of positive numbers using 4 different methods

arr = np.random.uniform(0, 10, 10)

# method 1
arr1 = arr - arr % 1

# method 2
arr2 = np.floor(arr)

# method 3
arr3 = np.ceil(arr) - 1

# method 4
arr4 = arr.astype(int)

print(f"Original Array: {arr}\nMethod 1: {arr1}\nMethod 2: {arr2}\nMethod 3: {arr3}\nMethod 4: {arr4}")


Original Array: [1.81890698 4.40709199 1.85873103 5.15355984 1.32231999 6.38671545
 6.94174264 4.97819423 2.26979973 8.30223047]
Method 1: [1. 4. 1. 5. 1. 6. 6. 4. 2. 8.]
Method 2: [1. 4. 1. 5. 1. 6. 6. 4. 2. 8.]
Method 3: [1. 4. 1. 5. 1. 6. 6. 4. 2. 8.]
Method 4: [1 4 1 5 1 6 6 4 2 8]


In [46]:
# Create a 5x5 matrix with row values ranging from 0 to 4

arr = np.zeros((5, 5))
arr += np.arange(5)

arr

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [51]:
# Consider a generator function that generates 10 integers and use it to build an array

def generate():
    for x in range(10):
        yield x

arr = np.fromiter(generate(), dtype=float, count=-1)

arr

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# Create a vector of size 10 with values ranging from 0 to 1, both excluded

arr = np.linspace(0, 1, 12)[1:-1]

arr

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

In [61]:
# Create a random vector of size 10 and sort it

random_arr = np.random.random(10)

sort_array = np.sort(random_arr)

sort_array

array([0.05101792, 0.20958459, 0.4210927 , 0.43396656, 0.60181216,
       0.71416569, 0.84585519, 0.88014779, 0.91899306, 0.98263144])

In [ ]:
# How to sum a small array faster than np.sum?

arr = np.arange(10)

# method 1
sum_array = np.add.reduce(arr) # faster than np.sum

%timeit sum_array

7.96 ns ± 0.0203 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)


In [ ]:
# Consider two random array A and B, check if they are equal
# is and == are not recommended as they do element-wise comparison
# using == will return a boolean array, if you want to check if all elements are equal
# .all() is the way to go if you want to check if any of the elements are equal (return just one boolean)
# use np.allclose or np.array_equal

A = np.random.randint(0, 2, 5)
B = np.random.randint(0, 2, 5)

# method 1
check_equality = np.array_equal(A, B)

# method 2
# check_equality = np.allclose(A, B)

check_equality

False

In [70]:
# Make an array immutable (read-only)

arr = np.zeros(10)
arr.flags.writeable = False

In [71]:
# Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

arr = np.random.random((10, 2))

X, Y = arr[:, 0], arr[:, 1]
R = np.sqrt(X**2 + Y**2)
T = np.arctan2(Y, X)

print(f"Cartesian Coordinates:\n{arr}\n\nPolar Coordinates:\n{np.column_stack((R, T))}")

Cartesian Coordinates:
[[0.31691195 0.87528061]
 [0.64045991 0.23732503]
 [0.07017913 0.5418463 ]
 [0.12652228 0.84190726]
 [0.54678682 0.86314501]
 [0.2243881  0.73806516]
 [0.80503179 0.99331663]
 [0.32116253 0.77851028]
 [0.17506066 0.79844445]
 [0.87424294 0.08660431]]

Polar Coordinates:
[[0.93088631 1.22341036]
 [0.68301689 0.35486719]
 [0.54637214 1.44199483]
 [0.8513611  1.42163203]
 [1.0217608  1.00612084]
 [0.7714209  1.27565366]
 [1.27857503 0.88971685]
 [0.84215416 1.17953107]
 [0.81741041 1.35495946]
 [0.87852207 0.09873992]]


In [74]:
# Create random vector of size 10 and replace the maximum value by 0

arr = np.random.random(10)

arr[arr.argmax()] = 0

arr

array([0.34073112, 0.09048205, 0.08243322, 0.        , 0.65584334,
       0.17002811, 0.66754041, 0.37495919, 0.71071619, 0.13190236])

In [80]:
#  Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area

arr = np.zeros((5, 5), [('x', float), ('y', float)])
arr['x'], arr['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))

arr

array([[(0.  , 0.  ), (0.25, 0.  ), (0.5 , 0.  ), (0.75, 0.  ),
        (1.  , 0.  )],
       [(0.  , 0.25), (0.25, 0.25), (0.5 , 0.25), (0.75, 0.25),
        (1.  , 0.25)],
       [(0.  , 0.5 ), (0.25, 0.5 ), (0.5 , 0.5 ), (0.75, 0.5 ),
        (1.  , 0.5 )],
       [(0.  , 0.75), (0.25, 0.75), (0.5 , 0.75), (0.75, 0.75),
        (1.  , 0.75)],
       [(0.  , 1.  ), (0.25, 1.  ), (0.5 , 1.  ), (0.75, 1.  ),
        (1.  , 1.  )]], dtype=[('x', '<f8'), ('y', '<f8')])

In [ ]:
# Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

X = np.arange(8)
Y = X + 0.5
C = 1.0 / np.subtract.outer(X, Y) # subtract.outer will give the outer product of two arrays, and X,Y don't have to be the same shape

C

array([[-2.        , -0.66666667, -0.4       , -0.28571429, -0.22222222,
        -0.18181818, -0.15384615, -0.13333333],
       [ 2.        , -2.        , -0.66666667, -0.4       , -0.28571429,
        -0.22222222, -0.18181818, -0.15384615],
       [ 0.66666667,  2.        , -2.        , -0.66666667, -0.4       ,
        -0.28571429, -0.22222222, -0.18181818],
       [ 0.4       ,  0.66666667,  2.        , -2.        , -0.66666667,
        -0.4       , -0.28571429, -0.22222222],
       [ 0.28571429,  0.4       ,  0.66666667,  2.        , -2.        ,
        -0.66666667, -0.4       , -0.28571429],
       [ 0.22222222,  0.28571429,  0.4       ,  0.66666667,  2.        ,
        -2.        , -0.66666667, -0.4       ],
       [ 0.18181818,  0.22222222,  0.28571429,  0.4       ,  0.66666667,
         2.        , -2.        , -0.66666667],
       [ 0.15384615,  0.18181818,  0.22222222,  0.28571429,  0.4       ,
         0.66666667,  2.        , -2.        ]])

In [83]:
# Print the minimum and maximum representable value for each numpy scalar type

for dtype in [np.int8, np.int32, np.int64]:
    print(f"Minimum value of {dtype} : {np.iinfo(dtype).min}")

for dtype in [np.float32, np.float64]:
    print(f"Minimum value of {dtype} : {np.finfo(dtype).min}")

for dtype in [np.int8, np.int32, np.int64]:
    print(f"Maximum value of {dtype} : {np.iinfo(dtype).max}")

for dtype in [np.float32, np.float64]:
    print(f"Maximum value of {dtype} : {np.finfo(dtype).max}")

Minimum value of <class 'numpy.int8'> : -128
Minimum value of <class 'numpy.int32'> : -2147483648
Minimum value of <class 'numpy.int64'> : -9223372036854775808
Minimum value of <class 'numpy.float32'> : -3.4028234663852886e+38
Minimum value of <class 'numpy.float64'> : -1.7976931348623157e+308
Maximum value of <class 'numpy.int8'> : 127
Maximum value of <class 'numpy.int32'> : 2147483647
Maximum value of <class 'numpy.int64'> : 9223372036854775807
Maximum value of <class 'numpy.float32'> : 3.4028234663852886e+38
Maximum value of <class 'numpy.float64'> : 1.7976931348623157e+308


In [ ]:
# How to print all the values of an array?

arr = np.arange(100)  # Array with values from 0 to 99

# Set NumPy to print all elements
np.set_printoptions(threshold=np.inf)

# Print all values
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
# How to find the closest value (to a given scalar) in a vector?

arr = np.arange(100)

# method 1
scalar = np.random.uniform(0, 100) # random scalar
closest_value = arr[(np.abs(arr - scalar)).argmin()]

# method 2
# closest_value = arr.flat[np.abs(arr - scalar).argmin()]
closest_value

np.int64(9)